### ISSUE TITLE
Namespace problems

### ISSUE THREAD

**Issue by jamieorc** [kyleburton/clj-xpath#13]
I've been using with-namespace-context to no avail. Looking at the codebase, I notice that the two tests you have are commented out. Curious if it's not fully implemented right now. If you expect that it should work, I'll follow up with examples.

**Comment by mortalisk** [comment]
I got a similar problem. I found that I had to wrap the 'with-namespace-context' macro around the parsing of the document (using xml->dox), and not just around the xpath function.

In all examples, I guess a string is passed to the xpath function, and thus the parsing happens inside, while in real situations, one would usually want to parse once, and then run several xpaths.

It would be nice not having to know all namespaces at the point of parsing.
