### ISSUE TITLE
can extension functions be defined or added?

### ISSUE THREAD

**Issue by nicferrier** [kyleburton/clj-xpath#24]
for example exslt provides a bunch of extension xpath functions.

having a regex match would be great:
```
($x "//h2[regexp:match(text(), '^big title$')]" node)
```

**Comment by kyleburton** [comment]
It looks like regexes aren't supported in XPath 1, but they are in XPath 2, and it looks like XPath 2 isn't part of the JDK...I haven't implemented extension functions myself, but it does seem possible:

    https://xml.apache.org/xalan-j/xpath_apis.html

If that API is available in the JDK's XPath implementation, it should be possible.  If you do take the time to code up an example, I'll be happy to add it to the repository.

**Comment by kyleburton** [comment]
Hi nicferrier,

I've read the contents of that URl and written up an example of how to use extension functions here:

    https://github.com/kyleburton/clj-xpath/blob/master/examples/extension_functions.clj

The second example will work with the upcoming 1.4.6 release of clj-xpath.  Would you mind trying out these approaches and seeing if they meet your needs?

With the first example, I'm considering this issue closed.

Best Regards,

Kyle
