### ISSUE TITLE
no results returned when using map under with-namespace-context

### ISSUE THREAD

**Issue by mnewt** [kyleburton/clj-xpath#30]
I'm getting this error:
```
=> RuntimeException Error, more (or less) than 1 result (0) from xml({:node #ob...) for xpath(.//nc:PersonGivenName)  clj-xpath.core/throwf (core.clj:27)
```
When I try to map over a list created with `$x` inside `with-namespace-context`. If I stop using the namespace or the map, the problem goes away. This is the complete example code:
```clj
(ns testing
  (:require [clj-xpath.core :as xp]))

(def ^:dynamic xml-doc
  (slurp "xmlns-test.xml")

(xp/with-namespace-context (xp/xmlnsmap-from-root-node xml-doc)
  (xp/$x "//lexsdigest:Person" xml-doc))

(xp/with-namespace-context (xp/xmlnsmap-from-root-node xml-doc)
  (xp/$x "//lexsdigest:Person/nc:PersonName/nc:PersonGivenName" xml-doc))
    
(xp/with-namespace-context (xp/xmlnsmap-from-root-node xml-doc)
  (xp/$x:text "./nc:PersonName/nc:PersonGivenName"
    (first (xp/$x "//lexsdigest:Person" xml-doc))))
; => "Bob"
(xp/with-namespace-context (xp/xmlnsmap-from-root-node xml-doc)
  (map
    #(xp/$x:text "./nc:PersonName/nc:PersonGivenName" %)
    (xp/$x "//lexsdigest:Person" xml-doc)))
; => RuntimeException Error, more (or less) than 1 result (0) from xml({:node #ob...) for xpath(./nc:PersonName/nc:PersonGivenName)  clj-xpath.core/throwf (core.clj:27)
```
And here is a gist with sample xml as well.
https://gist.github.com/mnewt/1c28e4f893aec8ce2c70

Am I doing something wrong?

**Comment by mnewt** [comment]
working example with namespaces removed:
https://gist.github.com/mnewt/af16a07f513a3d12bd41

**Comment by kyleburton** [comment]
Thanks for reporting this and especially for the test case.

**Comment by kyleburton** [comment]
Hi Matthew,

I've taken a look at your example.  My understanding of xml namespaces is that a document may have a default namespace and multiple additional namespaces though the additional namespaces require prefixes.  In your example document you have `xmlns:lexsdigest="http://lexs.gov/digest/4.0"` in the `doPublish` tag, though the document doesn't use the `lexsdigest` prefix on the tags.  I believe that youre xml and your xpath must both be using the declared prefix, if you put `lexsdigest` onto the `Person` tag (see the file `fixtures/namespace1.xml` in the clj-xpath project for an example) then your example works:

```xml
...
  <lexsdigest:Person>
    ...
  </lexsdiget:Person>
...
```

```clojure
(let [xml-doc (slurp "fixtures/namespace3.xml")]
   (xp/with-namespace-context (xp/xmlnsmap-from-root-node xml-doc)
     (->>
      (xp/$x "//lexsdigest:Person" xml-doc)
      first
      (xp/$x:text "//lexsdigest:PersonGivenName"))))
  ;; => "Bob"
```

This meets my understanding of how to use xpath with xml namespaces.  Does this meet your understanding?

Kyle

**Comment by mnewt** [comment]
Hi Kyle,

Thanks so much for your help! I'm having trouble reproducing your results. I see two issues.

1) Both the lexsdigest and the nc namespaces are specified in the document. Can't I nest a tag from one inside a tag from another? That appears to be the intent of this XML spec, near as I can tell (I didn't write it).

2) After changing the sample XML document per your suggestion (https://gist.github.com/mnewt/31cebcf629bf2e894d9b), I'm still seeing the same unexpected behavior (it's not finding the nodes):

```clj
(let [xml-doc (slurp "xmlns-test2.xml")]
 (xp/with-namespace-context (xp/xmlnsmap-from-root-node xml-doc)
   (->>
    (xp/$x "//lexsdigest:Person" xml-doc)
    first
    (xp/$x:text* "//lexsdigest:PersonGivenName"))))
; => ("Bob" "Bubba")
```
```clj
(let [xml-doc (slurp "xmlns-test2.xml")]
 (xp/with-namespace-context (xp/xmlnsmap-from-root-node xml-doc)
   (->>
    (xp/$x "//lexsdigest:Person" xml-doc)
    (map #(xp/$x:text* "//lexsdigest:PersonGivenName" %)))))
; => (() ())

Note that on the second gist (https://gist.github.com/mnewt/af16a07f513a3d12bd41) I intentionally removed the namespaces from the tags and that example doesn't have this issue.

**Comment by mnewt** [comment]
I narrowed down the problem a little. This works:
```clj
(let [xml-doc (slurp "xmlns-test2.xml")]
 (xp/with-namespace-context (xp/xmlnsmap-from-root-node xml-doc)
   (->>
    (xp/$x "//lexsdigest:Person" xml-doc)
    (map
      #(xp/with-namespace-context (xp/xmlnsmap-from-root-node xml-doc)
        (xp/$x:text "./lexsdigest:PersonName/lexsdigest:PersonGivenName" %))))
; => ("Bob" "Bubba")
```
What is going on here to break the context?

**Comment by mnewt** [comment]
I'm back at it. Can you help me figure out whether I'm doing something really dumb or whether this is a bug?

I ran this from the current master branch using the test fixtures. and was able to reproduce the same issue.

```clj
(ns clj-xpath.test.core
  (:use [clojure.test]
        [clj-xpath.core :as xp
         :only [$x $x:tag $x:text $x:attrs $x:attrs* $x:node $x:tag? $x:text? $x:tag+ $x:text+ xp:compile tag xml->doc *xpath-compiler* *namespace-aware* nscontext xmlnsmap-from-root-node with-namespace-context abs-path]]))

(def xml-fixtures {:simple (tag :top-tag "this is a foo")
                   :attrs  (tag [:top-tag :name "bobby tables"]
                             "drop tables")
                   :nested (tag :top-tag
                             (tag :inner-tag
                               (tag :more-inner "inner tag body")))
                   :namespaces (slurp "fixtures/namespace1.xml")})

(with-namespace-context
    (xmlnsmap-from-root-node (:namespaces xml-fixtures))
    ($x:text "./atom:title"
      (first
        ($x "//atom:feed" (:namespaces xml-fixtures))))
; => "BookingCollection"

(with-namespace-context
  (xmlnsmap-from-root-node (:namespaces xml-fixtures))
  (map
    #($x:text "./atom:title" %)
    ($x "//atom:feed" (:namespaces xml-fixtures)))
; => RuntimeException Error, more (or less) than 1 result (0) from xml({:node #ob...) for xpath(./atom:title)  clj-xpath.core/throwf (core.clj:28)

(with-namespace-context
    (xmlnsmap-from-root-node (:namespaces xml-fixtures))
    (map
      #(with-namespace-context
          (xmlnsmap-from-root-node (:namespaces xml-fixtures))
          ($x:text "./atom:title" %))
      ($x "//atom:feed" (:namespaces xml-fixtures))))
; => ("BookingCollection")
```

Should I be doing something different? I'm open to a different approach. Cheers.

**Comment by kyleburton** [comment]
Thank you for the examples!  I believe I've tracked down the issue you're hitting.  Clojure's `map` is lazy.  In your second example where you get the exception because no element is found, I believe it is because the map is lazy and the inner xpath `./atom:text` is not evaluated until after the code has escaped the 'with-namespace-context'.  If you change that from a `map` to a `mapv` the code works:

```clojure
  (with-namespace-context
    (xmlnsmap-from-root-node (:namespaces xml-fixtures))
    (mapv
     #($x:text "./atom:title" %)
     ($x "//atom:feed" (:namespaces xml-fixtures))))
  ;; => ["BookingCollection"]                                                                                                   
```

This is a trade-off of my api.  I used dynamic vars to reduce the number of LOC and arguments that have to be passed around.  An implication is that lazy evaluation can be executed after the binding has returned to its prior state (in this case going back to being namespace unaware) and the newly compiled xpath expression will not be namespace aware. 

You can avoid this by capturing the namespace awareness by pre-compiling your xpath and pre-building your DOM object:

```clojure

  (let [xml-str       (:namespaces xml-fixtures)]
   (with-namespace-context (xmlnsmap-from-root-node xml-str)
     (let [xml-doc       (xp/xml-bytes->dom (.getBytes ^String xml-str ^String xp/*default-encoding*))
           atom-title-xp (xp/xp:compile "./atom:title")
           atom-feed-xp  (xp/xp:compile "//atom:feed")]
       (map
        #($x:text atom-title-xp %)
        ($x atom-feed-xp xml-doc)))))
  ;; => ("BookingCollection") 
```

Does this all make sense?  This is definitely a leaky abstraction in the api of clj-xpath wrt lazy evaluation.

**Comment by mnewt** [comment]
That makes all kids of sense. Thanks especially for giving me two examples of how to address the issue. Another way would be to wrap the lazy sequence in `doall`.

```clj
(with-namespace-context
  (xmlnsmap-from-root-node (:namespaces xml-fixtures))
  (doall
    (map
      #($x:text "./atom:title" %)
      ($x "//atom:feed" (:namespaces xml-fixtures))))
 ;; => ("BookingCollection") 
```

I expected that the call to `binding` in `with-namespace-context*` would create a closure for everything inside it so that when the lazy sequence gets realized, the calls up the chain would still see the desired values for those vars. Now I know that is not the case. Here is a good treatment of the subject:

http://cemerick.com/2009/11/03/be-mindful-of-clojures-binding/

**Comment by mnewt** [comment]
Oh, and I see you already have an issue to address the larger context of using dynamic vars or an explicit API: #21.

**Comment by kyleburton** [comment]
Your earlier reply makes me wonder if I'm not thinking about this correctly ... I wonder if I could close over the dyn var w/o having to do all the work of splitting the api apart.  Thanks for the idea!  (oh, and if you're feeling inspired, and you've signed the contributor agreement, I'm happy to take a pull request for #21 :)
