### ISSUE TITLE
Version 1.4.7 dependencies incorrect

### ISSUE THREAD

**Issue by benrady** [kyleburton/clj-xpath#33]
Thanks for the new release to include the fix for #27. I think there might be an issue with the project information though. 

When trying to use 1.4.7, I get an error saying schema/core could not be found on the classpath. Looking on the [clojars website](https://clojars.org/com.github.kyleburton/clj-xpath/versions/1.4.7), the only dependency listed for version 1.4.7 is xalan. However, the project.clj on Github lists prismatic/schema as well.

Additionally, if I add the dependency manually (to a project that uses clj-http), I get this error:

`java.lang.NoClassDefFoundError: IllegalName: compile__stub.clj_http.headers.clj-http.headers/HeaderMap, compiling:(clj_http/headers.clj:105:1)`

I'm not sure if this error is related to the dependency issue or not.

**Comment by kyleburton** [comment]
Thanks for reporting this, I'll take a look.  The test suite didn't catch this.

**Comment by kyleburton** [comment]
Odd, the project file lists schema as a dependency.  I just updated it to a newer version of prismatic/schema (1.1.3) and released 1.4.8 to clojars.  When I look at this tag/sha on github:

https://github.com/kyleburton/clj-xpath/blob/12f0ff978845ebaacb01c013e384f0e2dc4ac15a/project.clj

I see the 2 dependencies ... I'll keep looking.

**Comment by kyleburton** [comment]
Ok, I think I found the issue and just released [1.4.9](https://clojars.org/com.github.kyleburton/clj-xpath/versions/1.4.9).  If a dependency is listed in both the `:dev-dependencies` and `:dependencies`, it will show up in the pom.xml file with scope `<test>`, which then doesn't show up in the UI for clojars -- and is hopefully the source of your error.  

If not, please re-open this issue or open a new one.

Thanks!
