### ISSUE TITLE
API Documentation calls it $x:compile where it's xp:compile

### ISSUE THREAD

**Issue by Vaelatern** [kyleburton/clj-xpath#35]
Title says it all. I had to read the code to figure out what the function is called.

**Comment by kyleburton** [comment]
Thanks for finding this!  I've updated the gh-pages branch and it looks like the docs are updated: http://kyleburton.github.io/clj-xpath/site/documentation/

Best Regards,

Kyle

**Comment by Vaelatern** [comment]
Thank you!
